name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install packages
      run: npm install

    - name: Check code style
      run: npm run lint

    - name: Build production
      run: npm run build

    - name: Run unit tests
      run: npm run test:unit